import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { AddressAutocomplete, type AddressSuggestion } from "@/components/address-autocomplete";
import { ScreenContainer } from "@/components/screen-container";
import { colors, PrimaryButton } from "@/components/urbico-ui";
import { useUrbico } from "@/lib/urbico-context";

export default function FavoritesScreen() {
  const { favorites, addFavorite, removeFavorite } = useUrbico();
  const [label, setLabel] = useState(""); const [address, setAddress] = useState(""); const [place, setPlace] = useState<AddressSuggestion | null>(null);
  const add = () => { if (!label.trim() || !address.trim()) return; addFavorite({ label: label.trim(), address: address.trim(), latitude: place?.latitude, longitude: place?.longitude }); setLabel(""); setAddress(""); setPlace(null); };
  const selectAddress = (selected: AddressSuggestion) => { setPlace(selected); setAddress(selected.address); };
  return <ScreenContainer><View style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color={colors.text} /></Pressable><Text style={styles.title}>Locais salvos</Text><View style={styles.back} /></View><Text style={styles.copy}>Salve os lugares que você acessa com frequência para planejar a viagem mais rapidamente.</Text><View style={styles.form}><View style={styles.labelRow}><TextInput value={label} onChangeText={setLabel} onSubmitEditing={add} placeholder="Nome do local" placeholderTextColor={colors.muted} style={styles.input} returnKeyType="done" /><Pressable accessibilityLabel="Salvar local" onPress={add} style={({ pressed }) => [styles.inlineSend, pressed && styles.pressed]}><MaterialIcons name="send" size={17} color="#FFFFFF" /></Pressable></View><View style={styles.divider} /><AddressAutocomplete value={address} onChangeText={(text) => { setAddress(text); setPlace(null); }} onSelect={selectAddress} onSubmit={add} placeholder="Endereço" compact /><PrimaryButton label="Salvar local" icon="add" onPress={add} style={styles.addButton} /></View><FlatList data={favorites} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.favorite}><View style={styles.favoriteIcon}><MaterialIcons name={item.label === "Trabalho" ? "business-center" : "place"} size={21} color={colors.blue} /></View><View style={{ flex: 1 }}><Text style={styles.favoriteLabel}>{item.label}</Text><Text style={styles.favoriteAddress}>{item.address}</Text></View><Pressable onPress={() => removeFavorite(item.id)} style={({ pressed }) => [styles.delete, pressed && styles.pressed]}><MaterialIcons name="delete-outline" size={20} color={colors.muted} /></Pressable></View>} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ screen: { flex: 1, padding: 20, paddingTop: 10 }, header: { height: 50, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, title: { color: colors.text, fontSize: 18, fontWeight: "700" }, copy: { marginTop: 15, color: colors.muted, fontSize: 13, lineHeight: 19 }, form: { marginTop: 20, padding: 14, borderRadius: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border }, labelRow: { minHeight: 43, flexDirection: "row", alignItems: "center" }, input: { flex: 1, minHeight: 43, color: colors.text, fontSize: 14, paddingHorizontal: 4 }, inlineSend: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.blue, alignItems: "center", justifyContent: "center" }, divider: { height: 1, backgroundColor: colors.border, marginBottom: 9 }, addButton: { marginTop: 12 }, list: { paddingTop: 16, gap: 10 }, favorite: { minHeight: 70, padding: 13, borderRadius: 16, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", gap: 11 }, favoriteIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: colors.blueSoft, alignItems: "center", justifyContent: "center" }, favoriteLabel: { color: colors.text, fontSize: 14, fontWeight: "700" }, favoriteAddress: { marginTop: 3, color: colors.muted, fontSize: 11, lineHeight: 15 }, delete: { width: 39, height: 39, alignItems: "center", justifyContent: "center" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
