import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { colors } from "@/components/urbico-ui";
import { useUrbico } from "@/lib/urbico-context";

export default function HistoryScreen() {
  const { tripHistory } = useUrbico();
  return <ScreenContainer><View style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color={colors.text} /></Pressable><Text style={styles.title}>Histórico de viagens</Text><View style={styles.back} /></View><FlatList data={tripHistory} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="history" size={34} color={colors.blue} /><Text style={styles.emptyTitle}>Ainda não há viagens</Text><Text style={styles.emptyText}>As viagens encerradas serão exibidas neste histórico.</Text></View>} renderItem={({ item }) => <View style={styles.trip}><View style={styles.tripIcon}><MaterialIcons name="directions-bus" size={21} color={colors.cyan} /></View><View style={{ flex: 1 }}><Text style={styles.tripTitle}>Acompanhamento encerrado</Text><Text style={styles.tripDate}>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.endedAt))}</Text></View></View>} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ screen: { flex: 1, padding: 20, paddingTop: 10 }, header: { height: 50, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, title: { color: colors.text, fontSize: 18, fontWeight: "700" }, list: { paddingTop: 20, gap: 10 }, empty: { marginTop: 20, padding: 30, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card, alignItems: "center" }, emptyTitle: { marginTop: 11, color: colors.text, fontSize: 16, fontWeight: "700" }, emptyText: { marginTop: 5, color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "center" }, trip: { minHeight: 69, padding: 13, borderRadius: 17, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", gap: 11 }, tripIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: colors.blueSoft, alignItems: "center", justifyContent: "center" }, tripTitle: { color: colors.text, fontSize: 14, fontWeight: "700" }, tripDate: { marginTop: 4, color: colors.muted, fontSize: 11 }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
