import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { colors, InfoCard } from "@/components/urbico-ui";
import { trpc } from "@/lib/trpc";

export default function NextBusesScreen() {
  const [term, setTerm] = useState("");
  const [lineId, setLineId] = useState<number | null>(null);
  const linesQuery = trpc.transit.searchLines.useQuery({ term }, { enabled: term.trim().length >= 2 });
  const stopsQuery = trpc.transit.lineStops.useQuery({ lineId: lineId ?? 0 }, { enabled: !!lineId });
  const vehiclesQuery = trpc.transit.lineVehicles.useQuery({ lineId: lineId ?? 0 }, { enabled: !!lineId });

  return <ScreenContainer><View style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color={colors.text} /></Pressable><Text style={styles.title}>Próximos ônibus</Text><View style={styles.back} /></View><View style={styles.search}><MaterialIcons name="search" size={20} color={colors.muted} /><TextInput value={term} onChangeText={(value) => { setTerm(value); setLineId(null); }} placeholder="Busque por uma linha, como 875C" placeholderTextColor={colors.muted} style={styles.input} returnKeyType="search" /></View>{term.trim().length < 2 ? <View style={styles.empty}><MaterialIcons name="directions-bus" size={34} color={colors.blue} /><Text style={styles.emptyTitle}>Consulte uma linha</Text><Text style={styles.emptyText}>A pesquisa usa dados oficiais da SPTrans e mostra linhas, paradas e veículos disponíveis.</Text></View> : linesQuery.isLoading ? <ActivityIndicator color={colors.blue} style={styles.loading} /> : linesQuery.error ? <View style={styles.empty}><Text style={styles.emptyTitle}>Não foi possível consultar agora</Text><Text style={styles.emptyText}>Verifique o termo e tente novamente em instantes.</Text></View> : <FlatList data={linesQuery.data ?? []} keyExtractor={(line) => String(line.id)} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.noResults}>Nenhuma linha encontrada para esta busca.</Text>} renderItem={({ item }) => <Pressable onPress={() => setLineId(item.id)} style={({ pressed }) => [styles.line, lineId === item.id && styles.lineSelected, pressed && styles.pressed]}><View style={styles.lineBadge}><Text style={styles.lineBadgeText}>{item.label}</Text></View><View style={{ flex: 1 }}><Text style={styles.lineDestination}>{item.destination || "Destino não informado"}</Text><Text style={styles.lineOrigin}>{item.origin || "Origem não informada"}</Text></View><MaterialIcons name="chevron-right" size={21} color={colors.muted} /></Pressable>} />}{lineId ? <InfoCard style={styles.details}><Text style={styles.detailsTitle}>Detalhes da linha</Text><Text style={styles.detailsText}>{vehiclesQuery.isLoading ? "Consultando veículos…" : `${vehiclesQuery.data?.length ?? 0} veículos com posição disponível.`}</Text><Text style={styles.detailsText}>{stopsQuery.isLoading ? "Consultando paradas…" : `${stopsQuery.data?.length ?? 0} paradas retornadas pela SPTrans.`}</Text></InfoCard> : null}</View></ScreenContainer>;
}
const styles = StyleSheet.create({ screen: { flex: 1, padding: 20, paddingTop: 10 }, header: { height: 50, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, title: { color: colors.text, fontSize: 18, fontWeight: "700" }, search: { minHeight: 52, marginTop: 16, paddingHorizontal: 14, borderRadius: 16, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", gap: 9 }, input: { flex: 1, color: colors.text, fontSize: 14, paddingVertical: 10 }, empty: { marginTop: 24, padding: 28, borderRadius: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, alignItems: "center" }, emptyTitle: { marginTop: 10, color: colors.text, fontSize: 16, fontWeight: "700" }, emptyText: { marginTop: 5, color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "center" }, loading: { marginTop: 36 }, list: { paddingTop: 14, gap: 9, paddingBottom: 155 }, noResults: { color: colors.muted, fontSize: 13, textAlign: "center", marginTop: 24 }, line: { minHeight: 68, padding: 13, borderRadius: 16, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", gap: 11 }, lineSelected: { borderColor: colors.blue, backgroundColor: colors.blueSoft }, lineBadge: { paddingHorizontal: 8, paddingVertical: 6, borderRadius: 8, backgroundColor: colors.blue }, lineBadgeText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, lineDestination: { color: colors.text, fontSize: 14, fontWeight: "700" }, lineOrigin: { marginTop: 3, color: colors.muted, fontSize: 10 }, details: { position: "absolute", bottom: 18, left: 20, right: 20 }, detailsTitle: { color: colors.text, fontSize: 14, fontWeight: "700" }, detailsText: { marginTop: 5, color: colors.muted, fontSize: 12, lineHeight: 17 }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
