import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { useState } from "react";

import { ScreenContainer } from "@/components/screen-container";
import { colors, InfoCard, PrimaryButton } from "@/components/urbico-ui";

export default function SecurityScreen() {
  const [safeMode, setSafeMode] = useState(false);
  const share = () => Alert.alert("Compartilhar viagem", "Ao iniciar uma viagem identificada, o Urbico abrirá o compartilhamento nativo com rota, previsão e status disponíveis.");
  const emergency = () => Alert.alert("Emergência", "O Urbico não substitui os serviços oficiais de emergência. Em uma situação urgente, procure os canais oficiais e pessoas de confiança.");
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color={colors.text} /></Pressable><Text style={styles.title}>Segurança</Text><View style={styles.back} /></View><InfoCard style={styles.shareCard}><View style={styles.shareIcon}><MaterialIcons name="share" size={25} color={colors.cyan} /></View><Text style={styles.shareTitle}>Compartilhar minha viagem</Text><Text style={styles.shareText}>Envie o status disponível da sua viagem para alguém de confiança usando o compartilhamento do dispositivo.</Text><PrimaryButton label="COMPARTILHAR AGORA" icon="share" onPress={share} style={styles.shareButton} /></InfoCard><View style={styles.list}><SecurityItem icon="person-add" title="Contatos de confiança" subtitle="Adicione contatos em uma integração futura" onPress={() => Alert.alert("Contatos de confiança", "Esse cadastro será conectado ao catálogo de contatos do dispositivo em uma próxima etapa.")} /><SecurityItem icon="shield" title="Acompanhamento" subtitle="Ativo durante uma viagem" onPress={() => Alert.alert("Acompanhamento", "Inicie uma viagem para acompanhar atualizações relevantes.")} /><View style={styles.safeMode}><View style={styles.itemIcon}><MaterialIcons name="security" size={21} color={colors.text} /></View><View style={{ flex: 1 }}><Text style={styles.itemTitle}>Modo seguro</Text><Text style={styles.itemSubtitle}>{safeMode ? "Ativado" : "Desativado"}</Text></View><Switch value={safeMode} onValueChange={setSafeMode} trackColor={{ false: "#33485C", true: colors.blue }} thumbColor="#FFFFFF" /></View></View><Pressable onPress={emergency} style={({ pressed }) => [styles.emergency, pressed && styles.pressed]}><MaterialIcons name="warning-amber" size={27} color="#FFFFFF" /><View><Text style={styles.emergencyTitle}>EMERGÊNCIA</Text><Text style={styles.emergencyText}>Precisa de ajuda? Toque para orientação.</Text></View></Pressable><Text style={styles.disclaimer}>O Urbico não substitui serviços oficiais de emergência.</Text></ScrollView></ScreenContainer>;
}
function SecurityItem({ icon, title, subtitle, onPress }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; subtitle: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.item, pressed && styles.pressed]}><View style={styles.itemIcon}><MaterialIcons name={icon} size={21} color={colors.text} /></View><View style={{ flex: 1 }}><Text style={styles.itemTitle}>{title}</Text><Text style={styles.itemSubtitle}>{subtitle}</Text></View><MaterialIcons name="chevron-right" size={21} color={colors.muted} /></Pressable>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingTop: 10, paddingBottom: 30 }, header: { height: 50, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center" }, title: { color: colors.text, fontSize: 18, fontWeight: "700" }, shareCard: { marginTop: 20 }, shareIcon: { width: 47, height: 47, borderRadius: 14, backgroundColor: colors.blueSoft, alignItems: "center", justifyContent: "center" }, shareTitle: { marginTop: 15, color: colors.text, fontSize: 17, fontWeight: "700" }, shareText: { marginTop: 6, color: colors.muted, fontSize: 12, lineHeight: 18 }, shareButton: { marginTop: 17 }, list: { marginTop: 15, overflow: "hidden", borderRadius: 17, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card }, item: { minHeight: 69, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 11, borderBottomWidth: 1, borderColor: colors.border }, safeMode: { minHeight: 69, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 11 }, itemIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: "#172A40", alignItems: "center", justifyContent: "center" }, itemTitle: { color: colors.text, fontSize: 14, fontWeight: "700" }, itemSubtitle: { marginTop: 2, color: colors.muted, fontSize: 10, lineHeight: 14 }, emergency: { marginTop: 21, minHeight: 88, padding: 18, borderRadius: 18, backgroundColor: colors.red, flexDirection: "row", alignItems: "center", gap: 15 }, emergencyTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, emergencyText: { marginTop: 4, color: "#FFE5E6", fontSize: 11, lineHeight: 16 }, disclaimer: { marginTop: 12, color: colors.muted, fontSize: 11, lineHeight: 16, textAlign: "center" }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
