import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { colors, PrimaryButton } from "@/components/urbico-ui";
import { useUrbico } from "@/lib/urbico-context";

export default function AgendaScreen() {
  const { appointments, addAppointment, removeAppointment } = useUrbico();
  const [title, setTitle] = useState(""); const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [address, setAddress] = useState("");
  const save = () => { if (!title.trim() || !date.trim() || !time.trim() || !address.trim()) return; addAppointment({ title: title.trim(), date: date.trim(), time: time.trim(), address: address.trim() }); setTitle(""); setDate(""); setTime(""); setAddress(""); };
  return <ScreenContainer><View style={styles.screen}><View style={styles.header}><Text style={styles.title}>Agenda</Text><MaterialIcons name="event" size={22} color={colors.text} /></View><Text style={styles.copy}>Registre compromissos para que o Urbico prepare o horário de saída quando houver dados de transporte.</Text><View style={styles.form}><TextInput value={title} onChangeText={setTitle} placeholder="Título do compromisso" placeholderTextColor={colors.muted} style={styles.input} /><View style={styles.divider} /><View style={styles.compactRow}><TextInput value={date} onChangeText={setDate} placeholder="Data" placeholderTextColor={colors.muted} style={[styles.input, styles.compactInput]} /><TextInput value={time} onChangeText={setTime} placeholder="Hora" placeholderTextColor={colors.muted} style={[styles.input, styles.compactInput]} /></View><View style={styles.divider} /><TextInput value={address} onChangeText={setAddress} placeholder="Endereço" placeholderTextColor={colors.muted} style={styles.input} /><PrimaryButton label="Adicionar compromisso" icon="add" onPress={save} style={styles.add} /></View><FlatList data={appointments} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="event-available" size={31} color={colors.blue} /><Text style={styles.emptyTitle}>Sua agenda está livre</Text><Text style={styles.emptyText}>Adicione um compromisso para calcular o melhor horário de saída.</Text></View>} renderItem={({ item }) => <View style={styles.appointment}><View style={styles.appointmentIcon}><MaterialIcons name="event" size={20} color={colors.cyan} /></View><View style={{ flex: 1 }}><Text style={styles.appointmentTitle}>{item.title}</Text><Text style={styles.appointmentMeta}>{item.date} · {item.time}</Text><Text numberOfLines={1} style={styles.appointmentAddress}>{item.address}</Text></View><Pressable onPress={() => removeAppointment(item.id)} style={({ pressed }) => [styles.delete, pressed && styles.pressed]}><MaterialIcons name="delete-outline" size={20} color={colors.muted} /></Pressable></View>} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ screen: { flex: 1, padding: 20, paddingTop: 14 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, title: { color: colors.text, fontSize: 23, fontWeight: "800" }, copy: { marginTop: 12, color: colors.muted, fontSize: 13, lineHeight: 19 }, form: { marginTop: 19, padding: 14, borderRadius: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border }, input: { minHeight: 42, color: colors.text, fontSize: 14, paddingHorizontal: 3 }, divider: { height: 1, backgroundColor: colors.border }, compactRow: { flexDirection: "row", gap: 12 }, compactInput: { flex: 1 }, add: { marginTop: 13 }, list: { paddingTop: 17, gap: 10, paddingBottom: 28 }, empty: { marginTop: 16, padding: 26, borderRadius: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, alignItems: "center" }, emptyTitle: { marginTop: 10, color: colors.text, fontSize: 15, fontWeight: "700" }, emptyText: { marginTop: 5, maxWidth: 260, color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "center" }, appointment: { minHeight: 78, padding: 13, borderRadius: 17, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", gap: 11 }, appointmentIcon: { width: 41, height: 41, borderRadius: 12, backgroundColor: colors.blueSoft, alignItems: "center", justifyContent: "center" }, appointmentTitle: { color: colors.text, fontSize: 14, fontWeight: "700" }, appointmentMeta: { marginTop: 3, color: colors.cyan, fontSize: 11, fontWeight: "600" }, appointmentAddress: { marginTop: 3, color: colors.muted, fontSize: 10 }, delete: { width: 39, height: 39, alignItems: "center", justifyContent: "center" }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
